sudo: required
services:
  - docker


before_install:
  - docker build -t bengrin25/docker-react -f Dockerfile.dev .

script:
  - docker container run bengrin25/docker-react npm run test -- --coverage
